### ISSUE TITLE
Comment appeler les démos de l'application ?

### ISSUE THREAD

**Issue by vfabry** [spelhate/storymap#11]
Bonjour,
Je viens de télécharger et d'installer l'application, qui me parait vraiment intéressante, mais je ne comprends pas comment on appelle les démos. Par exemple celle intitulée "mordelles", j'ai tenté https://sig.hautsdefrance.fr/ext/storymap-master/stories/mordelles/splash.html , j'arrive bien sur ce que j'imagine être la page d'accueil, mais ça ne donne rien quand je clique sur le bouton suivant.
Vincent

**Comment by spelhate** [comment]
Bonjour Vincent, Il y a un système de réécriture d'URL géré par Apache (fichier **.htaccess** à la racine du projet).
Pour appeler une story , il suffit juste dans ton cas d'appeler l'URL https://sig.hautsdefrance.fr/ext/storymap-master/mordelles/
Dans ton cas  ,il semble que le fichier **.htacess** ne soit pas pris en compte par apache, ce qui donne un 404

Exemple qui marche : https://kartenn.region-bretagne.fr/storymap/tournage_bzh/

J'attire ton attention que ce projet n'a connu aucune évolution depuis de nombreuses années ! Il s'agit d'une preuve de concept sans suite (faute de temps et de moyens).

**Comment by vfabry** [comment]
Merci Sébastien !

**Comment by hsquividant** [comment]
Bonjour Vincent,
... il y a quand même eu quelques suites à cette "preuve de concept" développée par Sébastien.
Si vous êtes intéressé, voici un page qui pointe vers quelques exemples d'implémentation de storymaps
[http://www.parchemins.bzh/index.php/outils/storytheque/](http://www.parchemins.bzh/index.php/outils/storytheque/)
Hervé

**Comment by vfabry** [comment]
Merci Hervé, je les trouve très bien ces exemples "en prod" !

**Comment by vfabry** [comment]
ça progresse : mon admin sys a pris en compte le .htacess
Mais il doit surement falloir le paramétrer correctement car pour l'instant j'obtiens ça : https://sig.hautsdefrance.fr/ext/storymap-master/mordelles/

**Comment by spelhate** [comment]
En renommant storymap-master en storymap, ça devrait améliorer les choses.
