### ISSUE TITLE
Installation de storymap sur un serveur web

### ISSUE THREAD

**Issue by Doctor-Who** [spelhate/storymap#14]
Bonjour,

Je tente de déployer storymap sur un serveur web standard.
Il est en production pour des applications mviewer, maplibre, etc.

Dans notre cas, nous avons bien une page d'accueil sur https://sig.hautsdefrance.fr/storymap/
Mais ensuite toutes les stories sont vides.

Par exemple sur le projet camaret, le serveur tente de chercher le chemin : /storymap/stories/stories/config.json (le chemin stories est en double). Comment résoudre cela ?

Une idée sur une configuration sur ce que j'aurai pu manquer ?

**Comment by spelhate** [comment]
Bonjour,
Dans le dépôt il y a un fichier .htaccess qui contient les règles de réécritures d'URL. Si vous utilisez apache commes erveur web et que votre configuration apache autorise la prise en compte de ce fichier .htaccess, ça doit marcher !

**Comment by Doctor-Who** [comment]
D'accord, effectivement avec Apache cela marche mieux qu'avec Nginx.
Cependant, je n'arrive pas à faire fonctionner les exemples. 
En chargeant à chaque fois le fichier splash.html il ne se passe rien lors du click des boutons. 
En me rendant directement sur cette page : https://sig.hautsdefrance.fr/storymap/stories/pe_brest/portal/storymap_europe.html j'arrive bien à parcourir la storymap.

Faut il PHP ? Quelle version est recommandée ?

**Comment by spelhate** [comment]
Bonjour,
je pense que vous n'utilisez pas les bonnes url. Dans votre exemple, la bonne url est : 
https://sig.hautsdefrance.fr/storymap/pe_brest/
sinon, Je note tégalement que les exemples suivants fonctionnent : 
https://sig.hautsdefrance.fr/storymap/tournage_bzh/
https://sig.hautsdefrance.fr/storymap/camaret/

**Comment by Doctor-Who** [comment]
C'était ça ! Un grand merci pour le coup de main.
